# configs/compute_errors.yaml

model_name: mnist_smalldensenet_1024_50.pt
device: "cpu" # this part is on cpu for the moment...

optimization: "non-linear"  # "linear", "non-linear"
method: "nlopt"             # "scipy", "ipopt", "nlopt" (<- best!)
use_multiprocessing: false   # true, false
batch_size: 4               # nb batches ≈ nb CPU cores  =>  batch_size ≈ nb samples / nb CPU cores

p: 0.7
start: 0
end: 40
bits: 16
tol: 1e-06
nb_iter: 50000
verbose: false

output_dir: results