model_class: VerySmallDenseNet
model_name: mnist_verysmalldensenet_32_30.pt
device: cpu
optimization: non-linear
method: nlopt
multiprocessing: true
batch_size: 4
p: 0.9
bits: 4
tol: 1.0e-15
nb_iter: 100000
verbose: false
test_subset:
  - 1
start: 0
end: null
output_dir: results
